### PR TITLE
Relay client-side fetch requests to the server using the Storybook channel API

### LINKED ISSUE #312: API requests should happen server-side and support a proxy agent
### Describe the bug

The browser network log is currently being flooded with Chromatic API calls as it polls for changes. This is annoying when attempting to work on a story that also makes network requests.

Furthermore, a HTTPS_PROXY isn't currently supported for these requests, even though the Chromatic CLI does support these.

### To reproduce

Just run the addon and look at the DevTools network tab.

### Environment

All versions.

### PR DESCRIPTION
**Pull request by ghengeveld**
Fixes #312 

This adds a `ChannelFetch` utility and `useChannelFetch` hook. ChannelFetch listens for messages on the `serverChannel`, performs `fetch` requests, and sends back a message with the response. The goal is relay client-side requests to the server, in order to avoid polluting the network request log in DevTools.

A `useChannelFetch` hook is included, which returns a `fetch` compatible function. This `fetch` replacement is passed to the URQL Client so all GraphQL requests will happen over the channel. Requests time out after 30 seconds (if they haven't already). The `signal` property is supported by means of a dedicated abort message.

<details>
  <summary>📦 Published PR as canary version: <code>1.9.0--canary.331.67b13f2.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @chromatic-com/storybook@1.9.0--canary.331.67b13f2.0
  # or 
  yarn add @chromatic-com/storybook@1.9.0--canary.331.67b13f2.0
  ```
</details>

### CODE REVIEW

File: src/utils/ChannelFetch.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import type { Channel } from "@storybook/channels";
+
+export const FETCH_ABORTED = "ChannelFetch/aborted";
+export const FETCH_REQUEST = "ChannelFetch/request";
+export const FETCH_RESPONSE = "ChannelFetch/response";
```
Comment (ndelangen) [inline src/utils/ChannelFetch.ts:5]: Please namespace these events, as-is are a bit too generic.

A common practice is to prefix them with the addon's name/id.

File: src/utils/useChannelFetch.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
+import { useChannel } from "@storybook/manager-api";
+
+const FETCH_ABORTED = "ChannelFetch/aborted";
+const FETCH_REQUEST = "ChannelFetch/request";
+const FETCH_RESPONSE = "ChannelFetch/response";
```
Comment (ndelangen) [inline src/utils/useChannelFetch.ts:5]: These events are duplicated, which could cause them to go out of sync.

A common practice is to have a `constants.ts` file, that's shared between manager/preview/server.

File: src/utils/useChannelFetch.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+        request.resolve(res);
+      }
+    },
+  });
+
+  return async (input: string | URL | Request, { signal, ...init }: RequestInit = {}) => {
+    const requestId = Math.random().toString(36).slice(2);
+    emit(FETCH_REQUEST, { requestId, input, init });
+
+    signal?.addEventListener("abort", () => emit(FETCH_ABORTED, { requestId }));
```
Comment (ndelangen) [inline src/utils/useChannelFetch.ts:44]: Maybe flip these statements around?

File: src/utils/graphQLClient.tsx [hunk 4]
```diff
@@ -56,56 +54,69 @@ export const getFetchOptions = (token?: string) => ({
...
+    fetchOptions: getFetchOptions(), // Auth header (token) is handled by authExchange
+    ...options,
+  });
 
-export const GraphQLClientProvider = ({ children }: { children: React.ReactNode }) => {
-  return <Provider value={client}>{children}</Provider>;
+export const GraphQLClientProvider = ({
+  children,
+  value = createClient(),
+  ...rest
```
Comment (ndelangen) [inline src/utils/graphQLClient.tsx:112]: rest has no types

File: src/utils/ChannelFetch.ts (hunk 1 above)
Comment (ghengeveld) [reply src/utils/ChannelFetch.ts:5]: I imagine this would be a generic Storybook utility, not something specific to this addon. I suppose I could prefix them until then.

File: src/utils/useChannelFetch.ts (hunk 2 above)
Comment (ghengeveld) [reply src/utils/useChannelFetch.ts:5]: Yes these should be in Storybook core/events eventually.

File: src/utils/ChannelFetch.ts (hunk 1 above)
Comment (ndelangen) [reply src/utils/ChannelFetch.ts:5]: Generic storybook APIs should not come from an addon.

This gives the impression it's a core feature, but then it's gone, if a users disabled/removed the addon.

Comment (ghengeveld) [reply src/utils/ChannelFetch.ts]: Ok, I namespaced them and moved to the addon constants file.

File: src/utils/graphQLClient.tsx (hunk 4 above)
Comment (ghengeveld) [reply src/utils/graphQLClient.tsx:112]: I was doing this because of the `key` prop, but I’m not sure it’s necessary to pass that down.

Comment (ndelangen) [reply src/utils/graphQLClient.tsx:112]: You could consider using `FC` from `react for that.

File: src/utils/useChannelFetch.ts (hunk 3 above)
Comment (ghengeveld) [reply src/utils/useChannelFetch.ts:42]: I guess mentally that makes sense. I'll also check for it to be aborted before emitting, we may not have to emit at all.
