### PR TITLE
Handle missing git user.email config

### LINKED ISSUE #352: "Git not detected" when running Storybook in Docker
### Describe the bug

When running Storybook inside a Docker container, the "Visual tests" tab displays "Git not detected".

Image

Git is, in fact, installed inside the container, and is able to see the project's repository. For example, `git status` displays modified files.

The Storybook output in the terminal where it was run includes:

```
[storybook] Unhandled promise rejection: Error: Command failed with exit code 1: git config user.email
[storybook]     at jt (/srv/app/node_modules/chromatic/dist/chunk-X7RBQNLE.js:55:57)
[storybook]     at /srv/app/node_modules/chromatic/dist/chunk-X7RBQNLE.js:56:1427
[storybook]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[storybook]     at async F (/srv/app/node_modules/chromatic/dist/chunk-CQ77PNYM.js:35:106)
[storybook]     at async Object.TJs (/srv/app/node_modules/chromatic/dist/chunk-Q3TNQW3L.js:1491:3219)
[storybook]     at async fe (/srv/app/node_modules/@chromatic-com/storybook/dist/preset.js:33:8923)
[storybook]     at async /srv/app/node_modules/@chromatic-com/storybook/dist/preset.js:37:293
[storybook]     at async Ae (/srv/app/node_modules/@chromatic-com/storybook/dist/preset.js:34:137) {
[storybook]   shortMessage: 'Command failed with exit code 1: git config user.email',
[storybook]   command: 'git config user.email',
[storybook]   escapedCommand: 'git config user.email',
[storybook]   exitCode: 1,
[storybook]   signal: undefined,
[storybook]   signalDescription: undefined,
[storybook]   stdout: '',
[storybook]   stderr: '',
[storybook]   cwd: '/srv/app',
[storybook]   all: '',
[storybook]   failed: true,
[storybook]   timedOut: false,
[storybook]   isCanceled: false,
[storybook]   killed: false
[storybook] }
```

And indeed, when `git config user.email` is run inside the container, it does exit with code 1. No user email is configured inside the container.

### To reproduce

1. Run Storybook inside a container
2. Authenticate the visual tests add-on with Chromatic
3. Visit the "Visual tests" Storybook tab in the Addons panel
4. See "Git not detected"

### Environment

Host OS: Arch Linux
Browser: Chrome 132.0.6834.83
Storybook version: 8.4.7
Visual Test Addon version: 3.2.4

Let me know if you would like information about docker (version, image details, etc.).

### PR DESCRIPTION
**Pull request by ghengeveld**
Fixes #352

Adds a screen to handle a missing Git user email:

image

### CODE REVIEW

File: src/screens/Errors/GitError.tsx [hunk 1]
```diff
@@ -74,67 +74,91 @@ export const CheckList = styled.ul({
...
+  fontSize: '12px',
+  background: theme.background.content,
+  border: `1px solid ${theme.appBorderColor}`,
+  borderRadius: 4,
 }));
 
 export const GitError = ({ gitInfoError }: { gitInfoError?: Error }) => {
-  const hasGitRepo = gitInfoError?.message.includes('one commit');
-  useTelemetry('Errors', hasGitRepo ? 'GitError' : 'GitNotFound');
+  console.log(gitInfoError?.message);
```
Comment (yannbf) [inline src/screens/Errors/GitError.tsx:94]: Is the log intentional?

**Review by yannbf — APPROVED** [review]

File: src/screens/Errors/GitError.tsx (hunk 1 above)
Comment (ghengeveld) [reply src/screens/Errors/GitError.tsx:94]: Nope, thank you.

**Comment by ghengeveld** [comment]
:rocket: PR was released in [`v4.0.0-next.8`](https://github.com/chromaui/addon-visual-tests/releases/tag/v4.0.0-next.8) :rocket:
